apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/part-of: nextcloud
resources:
  - repository.yaml
  - release.yaml
  - nextcloud-creds.secret.yaml
configMapGenerator:
  - name: ocis-values
    files:
      - values.yaml
