apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/part-of: nextcloud
configurations:
  - kustomizeconfig.yaml
resources:
  - repository.yaml
  - release.yaml
  - nextcloud-creds.secret.yaml
  - http-route.yaml
configMapGenerator:
  - name: nextcloud-values
    files:
      - values.yaml
