apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-creds
stringData:
    username: ENC[AES256_GCM,data:IZLXWSRrdpEEVty8LgLu,iv:nu1KLVjK4wiGqX1bj7s6WOwrllo2wpqEW3vwKqp8aKY=,tag:/hXqx8x0KUYmZu72Ebuiuw==,type:str]
    password: ENC[AES256_GCM,data:vMv964PO1Xs33N6CrV3NPJrOX2Y=,iv:9T2toG9fqxos8rN/OX189z+0MuBjwqFLwe+5Iux73SI=,tag:Mxo82WKv8xKCvRd1ZTO8hw==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRlk4Qk1aMlVMYlNMY21v
            OWttbjhKbEhmMXlHVFFNTmE0OXczMEdTMVhVCk5zWENlR0ErK1pIa0lQVmxlM1RR
            eWNvcERTRFQxVjBXaXZUNE8vRC9aNmMKLS0tIFkvM2YwSC9aMW12a2RldGJXVGxY
            YXZrM1RyNHgraXEwclRQOUlQdjdmRXcKu6vs4CXjPa/xma8hXOk8aK7RUg7dP5sM
            DCr2MQqKaJy1gmpcl1J+XbfJNi9CyiWFTeFjLXD/TKiWLOArR8xwXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T20:40:36Z"
    mac: ENC[AES256_GCM,data:cM7TOLLoGxL+932FrtfFT20v4fUXDoQy1CeT1JZjIDdej3QW+xJSzrT1vW4mehNG3Nw2FJ0q8nfSV8qnc7YqMCLscsSmSi8CGO+Wyyzl3vg5FdpOf/iNiRFkdm+PuoUeI1dTXcJXrDv/K49Id/YKRphVGCR2ws81SSlkkCgTUhk=,iv:5Lx3VaZtivSWpRKI3Zxx/SJuTXAtrSOyk4Bk60fHL+I=,tag:GBs8aIRp1o1vNCFVwc/N4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
