apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: iscsi-config-secret
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:BIQYJ+ZcNOHzsc3Bdo84Uc5O0aW81SGvtdVfb5nT0z3jV4sJ1j+ZHvkoDT/YNx8RE6h6XJk3WXDp9eeOIP5VghmwT8SoIy7QFBCT97HaLgHM8UDyqfWvowBNxGePRwPIiMijL7Ks53GjkZa02Aez2WXLUzJj1V1njw26eCaBJfdGxE3gfLKm/ARjAcPglOKSA+xE3JG1N1l4w23wSrzMc38OIzcrI7J0Nu6xI6jgsQMaszN0XjXcQsw4Benc/61J6qzo8bN6BQZHU30jST2cdbPjupXCqOTMgoqib4w279LUBXxVObsWBUUwAQCQXk6RZ05xBCfrxh6kQecHVIGAfov3ltB+QWsSVrijxxKqut0BJdMxNnb6pz8GUvNUQRsX8Lbc1rNZAt/AeN/+K+InlB40ZqT9GfV1/NwZVG0/jUdCmDXuIG+DypfIxx7+G78poFUNaJeZamCyMTvcZby7z5wm52rjV++yY3kRhEHiu/KEj1NN2ZF5/WbQ9KtyfACfeAz2gc2R4h3I5YsEernbXQKil/sJhK5u0Y8eozdvJGjXJzI7MoKKE2HGgjwsoCWZdiluoSUbYSolBB3OClejAxNK/LojWC5VTWpTE/ytSC5jUEVIo7J0VKKFRz9rTy93R1TqrUp+/HtDD1pL/Y//tU6y7yT7AtA99MXjiMd8kbVDMMSOLRZ9eXCKMugVs/9rBbzyCM4pOOiJrWRqSZByV/B1O/3quTvLho9yTjaNQ/pZlq2oj/mEOVjvc+xksPOmf7nTgc/bMS7keOrKUvIFgO3XlSl2HBhjitir9ZEnM4XSJ3px7RhzIWkNEKF2xwy9E1E5KWut7M94qNq3VDqFTT3D/iTKxaLiQme8annsPwQX3QIoGg3da8L8tGWXmufVd8ZUZY7MF3ullYzEtxIr2BEhn7uiH21CvY75PXgzR2xSsbpjQa7dOw4Q0BbdmR+jOoNIU5hNEgECJuz6/RW6Fcdiesk7fsfQUEKFk52UGZKtXdOSQUgOevIdj1WYrm0xeRxB0+2q1jbPayTOZWVduxov+a5QgymyBus1rU+2QX7bXs/pUf57A09aHDJTu7K/Oh72/Drq0Py5YSW+NGD3zfxugExQHyFhAAI6d1MepIU517oVvilcgxOepjUFLEwYklklTqmuhTJNsQoPfA5PxKjTk0Pq241PjkNRCbzsN6NHrS771uFGoRWPSSttdX7uuzCZPxWLzp3ssTpdRfrTKAelxOJboX906K4HmGL2KUA4mBAyClKAzcoCDmyddKsf7v4+MzW6+5kzZc6aQmPTO/PlykHyg5tmmyQ6ig1xmwgEPt9HP9g26twOeZPjKLEcuTVJziqqQWh2Q2Tc2UUAVoHtz633x3NgASt/K3sN98a03rbXFntWqGKX9yyZUWpHD8MnhSx7K7yH1/jTsSYfjSYLXMDuxOB9vsM20hF9UgoTv2NsrWmry7fbYZ31rV3PPSkC5iaLM3QDTNnatcyqI9eBG3QQTjL6adnjs1Z6X8vfvi1Tckbo2Ip8PAuCcmURNWHetb2f0i4XLxARPWP1OkN0eiSwsS6tECW4CBgzRhAZKtP6ZkDlV0vBgCm34nlvgbxO/JPPdGr6X5gimEK1+XUWDOyCBNeI1zYQiSIV5VKtHGkCzu48wOVIs4RLv2Rc/yWpVYsKK+os,iv:9ulXV/R27wtsqdoCMifNM8t/Xhjwha7zW8Zr5gA8lXY=,tag:v4CJVnf2hNej6U+kF5YWag==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUTB6OFluNGgwY3ZzRERU
            T3NLVXgydlU1Rk1LK3VnbittMHRSVFNURFNNCnk0cDVQVndFWXVUNVZCWHFUL0dU
            WXFxMkY1V3dnRTU4YnZROHFjVEk0UjgKLS0tIHZIRFF3ZGtFbnhNaGNrMlR1VG9B
            QkNabUlxemROa0hZUVgrZ1lraEdnU28K2Dvi2VLuxbH258d3PdwHTWdOVFwN+yzL
            YJviBW0IHHMo057jQmKI6dFJPc/Ycltaimg6zt/YFLaut7DHmD9jLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T02:59:46Z"
    mac: ENC[AES256_GCM,data:J9oo+yJM/AmqHeGvB7vzQ4eSGqZ+FA5dst9yUwOYBDbXoU9g7rjs5ardNo6EADlqtaiSasKMLddxahSMWOdSKERSbQGoB6YDNbxx6wTq3g8Y0DO8JtF1PQkh7M+oCzfd9j4wmVIybLjyGQdNhLhjRZGlHzGXZ6VTWTsx8Y+GYnw=,iv:HODpOWQdjbOjMhSY0mHSM9Pg0/9yoXRhUDzHFdH6Kdo=,tag:SZcWDw659o7hMLolR/Rvgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
