apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: iscsi-config-secret
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:nSsNs4gG7BKDffwjJ4AjVCtQJZPgpmhBD48WFA2BADy04nES2DBjJwQviS20FuZcRDbGwFTk64xRgSBOVp46rSHl+a998/lni6tADXki0mgvLgqzYnI7yQe/bEGR4tyGVXVbt7OgMtTMBIwDRi6fotUxnhQsH9lWRbyoIdiw5P5CGXsueh6R8bH3b48KtxpHatZXOaT8Hog/kvMtit1zZX+ZgNT5DH0pBGKOvNGtqYFyQmoX9A0WLL6Mvbf5udRcf7y/mYfqDBwcDyCYFraAVtFvHRnjAQgWGCjA82P87UtCxOLRvSKMA9GSf+zgoTdB98V8MEzEnxua/3sgFhP4JzHfU6Y6JyLCxeyw2pnV1vFNrex2lV4CWK18DQmyXZgT0wMdWySZQFSe8M3pk0pA0SXMoJiVm/l1s2exQ/gFWGfH1y5uosKIUqeAN9MlYt1G1hYXu4CQlzmLu3rjkdlXRxAnyNpWjfx7ACJ1e2OI8DWzafjuOUeHUHd17HQ1mwKQyN3VbUexNzrHQyCF4fIRJasnQlyb9PQFOs0u2aaeL6uX0EGrYTdA47LwmIqvF6tAfumRzfWYVJ2nuYCHWY0OasBrmudKvpx149Yo0YxD9FR3f744yOWDeBs2/Em2lOLJa7N2k8o+8rpB2BJfydI9QYaoQifWZ6sYUuSCup50YFqymRGCjXtzHpqa+2sgO0li1ZaoXdHzG1mtN8ois4OMo7KS63CRVlRk9EjyGAOMZiLeAtEus49dKB6j/jtawqs1QILeDYyX3tbEXVgoDARMMXaJMFltUrlHX5Ae1J4vPc4spEBR2x20caanzZIlH11p7pRRfSLV0xOooZBTheP1bInMSkPiLXWj/8KShsD6cwszLrYKm9fW/NiP7VaD4MuiKI5W4FXC0DfcAKldsix+cSss0ieD6L5mK6GmVDiogeB32/FxpDGklWmXe7mhFFa0ALRJHYrJ8ZD+TEBy2r3iUQSnHRjOLWYjQprGe5kZPcSHKPLWg5+fvRIp0zo8oIRHjhhII5kB9NVKh0cfV2REOaepnnPLBYVrNzPGBZ/7vQxF4eXjTOZXlPV+m/3lyyt6Oeq0BIhVncsK4uZUrRI0ydNWqLIlMvLmKZvG26Z7kbdOnVMS15KSZPy8eoI8sEBn7e8uvrwND8VLUlx37sHhCkjPKaorZ0RTbTMgOM0MV7PYxtfvhCcsDhfE7rtuiRj+X0T8hnHA2poXzqqieD+72+8ZmPtIYzw+c0VLrr/w/H+5PAaxceD66hm9D0iygOW0AJlfRllmnTZPVlfBP7LuZchzxVmOrzeV1rKrhCipvokfu8Kgt8UmV3iEs8KvkdMHdwxSMDGOY90lsLHILf9J8JvA2up7QRnA4qmb0YS0tkhbCXDW4MI35QUpNUBg3GO6Ap3bdH1i0xWadZJM+eHiNWqOYCn34sy2y5Ag61X0EafHlTc26hMyba2wf+8bo1GrxBpzlksw2tRKn2ycMd2A2y0KMopEQNApS6FYWA5JDGHh+bCOYM8Iau/IIe8F3S5OfpZAbg3i/u1rl0g3p144bZ7OmM+e0iC4V78brtVpx28gdU66RFLeOvifXpXpiEy5rnqswc3u0uDsBm7Z6fxCIlWwPo58SYiSG1/ky94ebOiG+fWBY1OVZWrzpa7IE2ewiA/38uZPmAmL8Q==,iv:/MgaMKSfztcBXVp8eopMie+DmvUAVGjn5rXydJ+DSNs=,tag:iUi7UVEtWOY0bMnRdqYgnQ==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUTB6OFluNGgwY3ZzRERU
            T3NLVXgydlU1Rk1LK3VnbittMHRSVFNURFNNCnk0cDVQVndFWXVUNVZCWHFUL0dU
            WXFxMkY1V3dnRTU4YnZROHFjVEk0UjgKLS0tIHZIRFF3ZGtFbnhNaGNrMlR1VG9B
            QkNabUlxemROa0hZUVgrZ1lraEdnU28K2Dvi2VLuxbH258d3PdwHTWdOVFwN+yzL
            YJviBW0IHHMo057jQmKI6dFJPc/Ycltaimg6zt/YFLaut7DHmD9jLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T03:53:21Z"
    mac: ENC[AES256_GCM,data:wOt81nmWdrKtqWuTX4dmJPz0iocHXKXUxbt2EYwYyLTj4vJxcnaS3miZfqdGnaBitbvz7RTL6HxsNbVTzE9aBjpqDirMbOdSpjrkIzgxT6xSZgUs93j0wsD3mm3cIYGt0wf2iuqRzC/IxxE7ViTedT8+vMc08zk44TxmHe05oS4=,iv:x6hpqTcMQcX72ma8+LOMpI2vfSYEfYatvLIxOQlmbEE=,tag:fZm0uUXFE7rgESavyl94pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
