apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: iscsi-config-secret
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:C4TdUYJVlOeddLl5dQVGV084of3tahK43ch6f9UVc+6sDIqViocQlc6/+DCQZjGlLbPI/obUfUdsADwcScmIgpaIWJoX8q8p1L/wAigpYIRue+2V4DiR98B+d3V+WA7zpX7yeArzLbUCdPopgel2i7AiDOYZuaKJaVQU8HOMAbcN+TRJI+APBBguC7YB2xMiKRkZwkbpb2efRCWN1Rc5FZ9IUp381wJZV2zzPQCtTsaHFgdahrrPbAXMuJKJTJ5D9b5vhS04wuQA4LADBUAADbzDkW7+qBAEOoIKUDk2n70quyJqtiuNiOj1N6710bGdbhC+TYVCXJO6GvMYvIZmj4GiD9EexXyjfFK2qsTbcLDY8RKCynVixIUp0d7myuR4E5KkepaDGhBd+Mr1jce+56ZHFvdfcRxs5tZCuGyQOXSlJLoOneyICQpIU/uTex/aq2ykvTyQs+juFRJNhuUder1LmHs7eaZKLZPPYEpn5FnaSdiXZ8S4i5M36WjY+1lwgCxFX7f0ZDB+xjn+AYm9TgkuHpGvRn5w+ZNLL7sRAtfKcFPfgDMAOfmtLUNdhBMoqVqTGq25dkQhx4Hn7ClS1qqxNrJgd5qcneVmujkqXAhx8H91CUOjJCtjekfA2kXLwbvVCIRZSyV3uuKgDDSXvbajY7Do15V1hW7X5UYt20l/Pcnt5rIaggSbCSab2dsLZfya7lP1c7g/bNTcdg2fRxrTJg0GIR26cMA5Aphv9qLztFQaGa6lKNIUpD4VXH5sQNoiPXomuCwGjYdokAqDKqE3bucLlp6Q5ZenDozm6BPpUfHnOeYVKd39+zKm1S7ayhm0lwH4Orpm88SI+tvboMr6N3G1/SUx3uzxQ2278QbDLbbBoG+jrGAB2JhzZpilA/h1lgSBzjn1T39Qk1CV9Ew+Ki7sz+eO2nyyjNeUeG4rLSyqxn3BG38TTFuFJzeBpaRNl7/a0XnykZj7mo5SQvHABvJr9uY8tdJL6Js44zurOKyrp0tjJ0dlp7MJxYRToknHUY7ew38yZ9Rhl6SXgD3ys7qvY4mzhGVRw9xMgcLH1QIl1M6xK7Mp//rScz9+bov7I02+rVPHla7wqz+IdiHcVyC7h9muECZTiNEkgHNmYrmfpr8TPFEHn+VXt29jx2FhXuy1IzH0mjZLCcJJRHbWzFCws143Vedtn4EUaEP7GnW8LN7YPoYMMvQSI8MD+XUn9+1HqC7c/W6gDT7SoOdm08uJK1BlEPbdnl5ILn56nNGRRnZUBwoeTllixujo5n20fHVGA7ghWMzXGzNJkdxju1pjNJAIETJ0eJ/zlBHSLHYrzdL9QuhsCAbhKoEdCj4AV7djBqUuAJKJ5vPCv34XfIbILBklmOmmKrXxc8PYb1UjjZRki0yDcrua3YpseJnLmj813VInT/Tt2NNl2Zw53qkl0SkAFnNM8CKLlrG39I7sSC+hfspOQogfqrVPMMGqt40+cFe+w9L0ctJCA9GSGTNyxvRoVcC7asmLowc/8RZuwjVZFfVNZw9cwxDLkSNoLHDsXG8peNCjmYEViMDhHHKuRfECwJzfyIXmjBqp5Q2iX0Fa34sy3xUvXEg8zd8W+Z16bnNikqCQ1cq/kw6AVavRH7biz2emiLP7PrqBVF8hnJ7G9yrP4sA6w9o76zgwhJ4P/mQ3zJw=,iv:ANwlKuuNQ+3t3wqxkOLVouX77mP2YsJHt8HP0wSJMo8=,tag:At9EqDCAu2SYuRsf8e4f/g==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUTB6OFluNGgwY3ZzRERU
            T3NLVXgydlU1Rk1LK3VnbittMHRSVFNURFNNCnk0cDVQVndFWXVUNVZCWHFUL0dU
            WXFxMkY1V3dnRTU4YnZROHFjVEk0UjgKLS0tIHZIRFF3ZGtFbnhNaGNrMlR1VG9B
            QkNabUlxemROa0hZUVgrZ1lraEdnU28K2Dvi2VLuxbH258d3PdwHTWdOVFwN+yzL
            YJviBW0IHHMo057jQmKI6dFJPc/Ycltaimg6zt/YFLaut7DHmD9jLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T10:31:37Z"
    mac: ENC[AES256_GCM,data:Go6r3cUYRN626Y1ZZPV2clCwAjWS9EwYLaEmMiDmRwDs1GMYDcvTgI7tf6fwBbQhmqfwAkU9kEw1at+wb0808+M75HE/dWAI5XlmjRSxa/IQad3Xh2Vtyhr5KbI+RBGAyghZTFlI9/gkDi1EDf49GwEcJ/nAu1FAFXxa0AM71wU=,iv:21+b1UIn/p8+NyzCUiIU8jQNMuPFU8i50AGTZl+mECo=,tag:ZEsXZwQ0Ip5DAy+tY2Aqvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
