apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: iscsi-config-secret
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:X7DpNhX3ZZaSyogrgHRpzXtcWhFDmvTL2GQKKiL3n9rmemXW8tAPwU9x677dfyCE44Yn588xQKg3fsZi9hs/dnYD9b7CIk3vP5wJnP/vUKT4IYbNjjD4hq8aM0MWjSliFmafxyja+9cQHdARsTgavd1oPUWbn1CkIXfeqi+5w7ySsC6b0yv0IjmMvSUG35u7VwFGxC9RnmULbZ5k5SRXIEcSECjQVAtGvdO4LAlB0EE8fLrFa1HGnkAQX+6aP64L1wY+x6/UdJp/ld+x9y0+VIupVsMyCBBRPlm9bnLQcMGeHeRmfUGznzNAAijtDlw5HFbaEPzV0CT9ZlMSfnirjoTESvJOdrlE6e08bfv33R+UpMHU9GJDB1hd/1CfNB/V4sCAe/ngQa+N2XcNznWpy/kIOwGSn3r7pw7gW2Ax+9p4T1gH20CuBC79oXTj0py7GSkYUTZswUY9vgXf5Mv+eloZLWYaXBxgweakicbGAlSs13tYe79BR51/hV8CXmtJXGEh9FAs4Nktqkvpb40jB6M5kEwKkYoIb6n6eURddunDldrBozrkrDzyZEgvcsFnqLjQFXub1/gpjSV85d5rR5OJr+TR80mHt+QbAsbFpZoojLXyflrUuvwSCggdMVV7l5GTyKWU5Ouk/n/ezJBRIi4OB0kpDOQ3GsJhXR1E9s3ckikYp/r+te2xjCHWDajH2qTe4C7T6ZOmxITHtYU0hUX/SeXsP32raT5/WwcplQRaIX71x12m/zUf91M1WTZRZVOB3hHouLEBxp269Jl+7fETjcigj/WetGvkm2Iv8TUIQ4sApQC+K+4gAZEKQtQTGLIfSgQDNpFetO+IPAoWRg/uo153o01or8rAhBeWgeBpPK5PuH2iJ8fTWAqdjQ/N11xR5KuJvBrKA3gCzOfC2rzTxhNSgHBjlzYSzLnzTQdQZUI556QPqjiwxnuNwAANWdjPrSpoUlOcLljtqrjmUiLyHb/RwQJmFu5TQq7PKzE6Z0mUycJ98ZBVehll4O6YcFaQ22aG7Hu+R3w9mgXhKeUBbKf8TiiKSIWzZbUvWGzo+8it/7m3ju5H/gW8jThW+1VNsmQ6C+VyOW68bvYguyfzqndtMfM6ZoUW1Hk/z3QZ/yj5eYKrYc4CkASVNRQH0ubhK3Uc9LRjpIggwMvLiLpNx8/pIslgW88eEcsBGoC2CiQtm/KVev+G1jinMuZ7+fYZyILudiGLOU4NgAkXT0//PlTS+YgutEsqzgNee1atmh7VavObP29gPZ44LTwu2eCWqvnnMNNljrJonqcgsTuKMyw8+PayqiwK7zM4IlRxRHqxeg7j2Fs+8CBce0aoRi0dgSiyLHSoc14JNq+HQi/tQ/WYb65Hkt6ntN9EhptPhXXc9TjCUpPARmx802ShmRsu8lZlDghziwKOBTj2Ds9tmha7VqAYkjDj61OXI91nw4EVyW7/WTWPX5GtQeW+mWN4iWwNmyhe07jmFIbd+hYdSRmXgC6vwu4efi6z2aHnYg2qVSxjx16hYAswqewhffWCLfwo5RQ+jvMoZqIEQBquxa19xzO5k5dbSzRoZXnQVuop/4mChhOLnjoUIOLf0d4Texmdm/xgqV0b3KwBPL3LrsPFnEfNh4QWyCNUaUQpDxtpkPkopvkRi/2uNnNW76gMpDej8Q==,iv:ineebbAlPggH9KNtOZ5VjNFgAugMVwi2fZn4lYg5qqw=,tag:SciBVj6NkvMpNq96hArj8w==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUTB6OFluNGgwY3ZzRERU
            T3NLVXgydlU1Rk1LK3VnbittMHRSVFNURFNNCnk0cDVQVndFWXVUNVZCWHFUL0dU
            WXFxMkY1V3dnRTU4YnZROHFjVEk0UjgKLS0tIHZIRFF3ZGtFbnhNaGNrMlR1VG9B
            QkNabUlxemROa0hZUVgrZ1lraEdnU28K2Dvi2VLuxbH258d3PdwHTWdOVFwN+yzL
            YJviBW0IHHMo057jQmKI6dFJPc/Ycltaimg6zt/YFLaut7DHmD9jLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T10:19:03Z"
    mac: ENC[AES256_GCM,data:LZ2prKtCqnYtHJpywLMgpOPJzZA5VgfIqpLYZp3CxL2TX2YfhEKjV1PAkPF2KwqSfKIXy9v7XyT/bv7VNVsCZSFvz+8vOYjvRUqqjyAsL4lhf7xZXgjbdtH5RmUsKwiULeWSIX8F+b3++Tg1mnHPDTiwNWMn5q7NuXWtrI3ixgc=,iv:tPTlXJRqQvJQ+oW+Uy90py/lcLhU8jHvVdv39m2cl8o=,tag:smczJSV96o9SjDi6apd9YA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
