apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: nfs-driver
resources:
  - iscsi-config-secret.secrets.yaml
  - iscsi-config.yaml
  - release.yaml
