apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: democratic-csi-iscsi-driver-config
    namespace: democratic-csi
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:2luw4luPuKp2tfNE5QkU4L0J93UZXcQDxtjfCf/Cigf9rZP4TeOcMGNpq6qNGudowFMyrwARJGPwdY29tNrmxhtIwcTLsJKP+tpYusaNkdlMNyBJ8p6YJGoG0lxBhv4Z/aaoePaRlkJ+r0yaj8K/eMPKRowjDHpoMhX70Cxa5aZFV9FgN4yRgiP7dv7mT2Za+IM9Xe/t++2ihJBDiSBNLqM3LFfNcBNqCEsCgF40ZflXmBYhyupMdIKDqLA3dcTQ3e+Abe9lEoL1ON+uUW/YdEE1ZuQwkAkCSs9JdYs9yBOqjzEhs65bp+UZtXzxXixySLepwUcbUtaR37N8mzhhhIq1gW2ejaamyLQZi7G3q0gsTO74dHpGRcQUUAqTcKxJTMcpuQUbWXRUp1VP/2l/p/3RbTvFo69sowHcfzvQ45zIE3UbGgBEu3ry0xWmA0DLyU05rvte+AbcZuSO1oZJyWXBo+A1AgBMtqy7J5nHXhPytjLcy0o52z7TGH0MYYrzKTL7RdLOzGtIkymBIA3Oipk5yIuSey+ZLbviBzEirgBzOcAv/X+ICCbl11qcwvHSSANNzK8OihfvSRvnwZi+Wkp4xWEDEZ9QpZ0Vq4s8jcy1t5oW/YKl9CuqoVKEwOoAgOlofdSmZ+vo3ipAbhiIz/IwLJK0vq9N1D+YEjuCH3qCQbLaIyD/9Z4XfO/UVdV9CDmtEMQfeIhYcWFkQH8vBg58paU5Tk4fkyZu9//FrgX3CnRCfjbzuD53wH61b3d22tUCLSdFRTYu7FCGMt4Q5xlD76ddEt+q5stiY6hiTrA3u/M+k8IcaUULLblQaJA+8bIuGuYMiIb4jg1tpLfyKrAiQcfdy+C4UTg7H36NK5W30pYRPN+c4WtMRcmq/v4nGpcyyGpvh42kZFEnoaKQNb4bGDucH8KJuW8miTCa1sKlFVyUnx3HMQStH8lDO14nN1NMfjoqNHgznldbbseCw3AawtICX90+TR0CmAB/o/dctJ3Ki3qR7YdvcT9gBgqsI3FjTsz+1xdx4auRO5S/d/yTsn5RjA0bcZK0BqI9pZbiaijTNX6k9gEJ8VW9nt60f2NUFErIp2XCQGvQx+HId61nQP1GmBY4gwvMq3mszLmUPwTGyY4elBULQbHTs0DpzLmXd9aSZOzhMN5pe6fFvAL/rfPhOc9xXthtu3NbKVKy6xhTIweZ6MzXAqWQaXDuHz+Pg5aNgEM4lLceiqr2z3jSM6NUA8C+EfTkYKhzJTkhObVVmpaPkajoyJ7PzKlo7Fs109knUwGrrBzi4ia6CGh36oPJrSjlPF9amOyT5gScxu6Wzsv6kzYiXxLHs0VCZ1lGlk2yaxpwgQ3r4J+CSSOh7Txt/GZx5keIOb0Ml1mJ0JSuCPN0/qBYw4EStI0KQa6y+bv76cu6cExODE1puaop4O5JSpleUYcOEQ819THSIGXOuloLcZMUCPHM2g4NZ1yq0J9V1R0ef05e3RgY9zSkK9v2i1O85DI7h5jK8J293ljYU7KMJB1O/1k0/l9CogVT/f7huhWzvCs0u/4YNmLBKFInUF89VcZFcFUob+Wt8fkoxEKOtf4+aGn31gMgY1GMADN0WhK4FupM+0N04EHglAMs8SJtZyEMZnRE4XDpZcOJ63Us3PUoiPNM4MDsOFWuBoO6G08=,iv:SpPFYw+keM4QJlWSL+QgSQLOritEgbWtv1hBqiBIPEY=,tag:ny2KNkddUuZwlhEh6lbT7g==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUTB6OFluNGgwY3ZzRERU
            T3NLVXgydlU1Rk1LK3VnbittMHRSVFNURFNNCnk0cDVQVndFWXVUNVZCWHFUL0dU
            WXFxMkY1V3dnRTU4YnZROHFjVEk0UjgKLS0tIHZIRFF3ZGtFbnhNaGNrMlR1VG9B
            QkNabUlxemROa0hZUVgrZ1lraEdnU28K2Dvi2VLuxbH258d3PdwHTWdOVFwN+yzL
            YJviBW0IHHMo057jQmKI6dFJPc/Ycltaimg6zt/YFLaut7DHmD9jLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T13:54:21Z"
    mac: ENC[AES256_GCM,data:ItqKvfdEKW8Kb2j5NlnmiQqCrgPW7tbKUDWQWxXmopW+bIQVJND7pWvpGVHp7xWXeBYEak81609Hu/JP3H8Dv1b5KitMbfiag6I9inneSbXIpW2LsKHNdyedomIqVb0BLiBV4keW43qwx+4YrzupfWeEcASQ3RaIapUyW2b2XmE=,iv:ghKNqW/DONbogVho/L1EbAWUt4GpNev6jK2sMvYkyQ4=,tag:I/0WLsLUGNsPJgrQth6rzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
