apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-base
  namespace: flux-system
spec:
  interval: 30m0s
  prune: true
  wait: true
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./base
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-configs
  namespace: flux-system
spec:
  interval: 30m0s
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure-base
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./configs
  decryption:
    provider: sops
    secretRef:
      name: sops-age
