apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi
resources:
  - namespace.yaml
  - repository.yaml
  - nfs/release.yaml
  - iscsi/release.yaml
secretGenerator:
  - name: democratic-csi-nfs-driver-config
    files:
      - nfs-driver-config.yaml=nfs/nfs-driver-config.secrets.yaml
  - name: democratic-csi-iscsi-driver-config
    files:
      - iscsi-driver-config.yaml=iscsi/iscsi-driver-config.secrets.yaml
configMapGenerator:
  - name: democratic-csi-nfs-config
    files:
      - nfs-config.yaml=nfs/nfs-config.yaml
  - name: democratic-csi-iscsi-config
    files:
      - iscsi-config.yaml=iscsi/iscsi-config.yaml
configurations:
  - kustomizeconfig.yaml
