apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
  - certificate.yaml
  - ca-secret.secret.yaml
  - ca-issuer.yaml
configurations:
  - kustomizeconfig.yaml
configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml
