apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: alerts
  app.kubernetes.io/part-of: monitoring
resources:
  - discord-webook.secrets.yaml
  - discord-alerts.yaml
