apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
labels:
  - pairs:
      app.kubernetes.io/name: alerts
      app.kubernetes.io/part-of: monitoring
resources:
  - discord-webook.secret.yaml
  - discord-alerts.yaml
