apiVersion: v1
kind: Secret
metadata:
    name: couchdb-secret
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:J3jWQ/cjF0c/Vj5K3g==,iv:eCKUC0yx/Y5Fh6h9gtuoXFrHMpHmRFV4EYty81NzkYU=,tag:luyzplgJDRWtHAvFuJ9JrQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:y4JYeoIHLvq+ssiQoFjJMiflHMY=,iv:TpavM9M6q+PV/1ZD7iedegUqKOZyzmF1yFRY0phZl50=,tag:rdH47e8zxgj6xAQ+7WYgGQ==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMEkyWjF4VXZnYXAyZytz
            ci9qNm9lYkpyTjhnVnhxSUd0WnhiWElWcEVZCkJ2TmhkK1c3OGd0M0tudHVBN0NB
            LzRFRURGWnhHL2xycWNCY2JGZGVpNDgKLS0tIFYwbkhQdm1VbThudGg2UmxjaWh2
            SWlpck14R3ptbC9mSVlOOFZXQktQWDQKlM0jS/K8kRnTTYZ0onrlfa3zDGTwR3CU
            fnkGWit64GSExwRFCYiV+r90VHIDlUFmZRgl0Va+sYd6FxcjhlsuzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T21:50:38Z"
    mac: ENC[AES256_GCM,data:P7a/rYGLZ5H4BnWQ0XsqLVS9zWaPGxEMeUZ6l2FHKve7jISWeZiDiP93U98AmVGKuwY0+4JSjqG3YSqeTckOOFW/NE1xVP+kHmwTQHWTQB+J2HInzNAmGObvR1FmkWSyY4ZZpfyKYdm+3UiPRikEbr5Y24Pw3n/K695rpDsW45w=,iv:O3yPW+5BLFldd0NTBCgvvjCTw/yZsqbE1nZmFk5LZKA=,tag:fpXD/qaPFMc9yftlORlNfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
