apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: couchdb
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - "couchdb.k8s.nyumbani.home"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: couchdb
          port: 5984
      filters:
        - type: CORS
          cors:
            maxAge: 3600
            allowCredentials: true
            allowOrigins:
              - app://obsidian.md
            allowHeaders:
              - accept
              - authorization
              - content-type
              - origin
              - referer
            allowMethods:
              - GET
              - PUT
              - POST
              - HEAD
              - DELETE
