apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: couchdb
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - "couchdb.k8s.nyumbani.home"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      backendRefs:
        - name: couchdb
          port: 5984
