apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: couchdb
      app.kubernetes.io/component: obsidian-livesync
resources:
  - statefulset.yaml
  - pvc.yaml
  - couchdb.secret.yaml
  - http-route.yaml
  - middleware.yaml
  - service.yaml
