apiVersion: v1
kind: StatefulSet
metadata:
  name: couchdb
spec:
  serviceName: couchdb
  selector:
    matchLabels:
      app.kubernetes.io/app: couchdb
  template:
    metadata:
      labels:
        app.kubernetes.io/app: couchdb
    spec:
      containers:
        - name: couchdb
          image: couchdb
          ports:
            - containerPort: 5984
              hostPort: 5984
          envFrom:
            - secretRef:
                name: couchdb-secret
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: couchdb-storage
              subPath: data
            - mountPath: /opt/couchdb/etc/local.d
              name: couchdb-storage
              subPath: etc
      volumes:
        - name: couchdb-storage
          persistentVolumeClaim:
            claimName: couchdb-pvc
