apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: democratic-csi-nfs-driver-config
    namespace: democratic-csi
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:OHRufhiAv+Si9q+rmNnWr2bQ7ycVD+aSrqpTyFgaggGS/Fq9EzvqgKeFci3DZ8eQWgS5sc4UM83W8ILDMtgcNu+inJ1vbRMBzknb9GMwmv+lkqT5iJjiXxa5WI1+uHeirOXe68+2cCEyaTeibcS1jwJtnAkiPhwpjPHVTODp0bUNbDgQt97qrcvvNn0DJ9jyZe72sWArY6/91Wu4TR9Zrou/4GUPcmHVfIreWYrhPSMygbiFThyd3QN7mLI9ZEq9U4pObcGXW/usonUfhxck+WTOYzt9YA0MHcT86qIgGSyV808hqs+rH9O+Jedwk1HE05o4siLgukGoXSmPhlfeVvABSoHKEy1m5lKT/CFaxIEaojrOnvv5AcAZHxUPJruaewQ9C0sk6k0upahW8YKxNi2VukeudrnEsY56+L+0yDwN+9z0eBo5UfsasBsZIAo+xHWz7BP+cgfdlfJdzQvKbS29oCV3J5ccIGKkhl63T3bGssSOkDr0WY02ACtt3XVYYZ8s80b8fozj5JOjqLnR7wndelasPo5OLEffkSAyI/GqMi3Qsihgm1nFVtXA7ca8TzaPSTecuCpmhYXhdsz8Gq4TAJeRo4P/HLazgCqCUW9qP3jtiLpLbeU9bG4GULUAneNSwdiJfps+LJaX7o0xgaryXIwmTJPHmiUT1RmygUTK9Q0KNB/cX60Jbg9W3swhgnK5QT4coNJ7vIT7Fl4fRYna9UzcP4ExCQ+8t6qfs9f9VSY1b1ldD/f7VYZ1V3IEjORye8SffC8AlltjZH1Cemoz90qfA7svrUyBL+TpS3Jmplrf65x6H2BIQWFfZIZgrio4xZGlSGnw8Ra9pr6hgVY9bXsSTNEr+kLI/a2e+kNYJPSGkbKxbeDF7ObSoKmlo1dJbuNlIA2fCJGys39mZrdSBSbaCsVet7OuCXSthBFGXk8AfPK1G3aZdmi3VHF8zTDUKHGlPLei4/xpm2tMwFnYA0M3qxDyJ9TjmZTbt70MFwc4oiwA1/NAi6S0+90CL5alGcoBhnPF7qVrMsBrT9eSCA5G0HSz/GX+FZGA8fwp9mZ58eK6FCRZHQoBEJeUdXNESyH8X764h1/b8IsMHU94Qo3X1EhXL+bnhu8LbHgL7yxKz6rfGj0tOC413CmUZVjowAtIeqngUrXcnzuivF+22IsEOSLbfGpI1+MxHy0M7jkMvGnP8C06OYPcID46MNINwCjvcpzhnAINfX2GkUr0XgoG3obm1eCtONuvuXGR5MUmxSm9jJa+O5ZiVzQsLH9l,iv:7caKMTtTip0DwMV+ZDXK16772dTRKFWbDpUojsiB9lI=,tag:ux0UIg03oxwwH5s1DxlgVQ==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1anE5RGYyOWJlR0NtcE5O
            TXlwSnJLZEtka3VXZjdLT0R5RVZYZDRKU0M4CjI2N2dqd3FRZ0o0ZnRVdDJTZzZP
            THlZYml6c1htTVh5eWMweFV1REVvMWcKLS0tIHFNUkJGZk03Q2ZBb0kwU0xrVzRt
            aVRVOHkzaDdKcnJHZ0I1RmtiTnlmY00KotBE+QRpWcjKL6C6zgshzdB6rzyaEId3
            LDu+lqpMSQp3eInmEezbJOtHxLqpggV/PEbOUfW2WelMDfCHIKcx+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T13:54:56Z"
    mac: ENC[AES256_GCM,data:x12uKH6vAYH9GoCBDZnA5ugtQKaJ6aWyAYkCjEs37Wc6vSN4WUJ5VqQo+7YQ5lCe1RbkP5cr7EqCJ0iXYJJ5tDgtJ3Kh/7mUWGzpf2FdKd3vkM9JRd54dUgFQ0Haa7TXgstgsAemvm++CPdmpH3HWHKD7VACbp1HodDur500fa0=,iv:ZMVIfO6Y2l0FfPAukF0RXZglq0Jalk62J6GAKD4CvGk=,tag:Pq5tlKVPyvoJNy4YqyTy6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
