apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: nfs-config-secret
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:KdiMK+P5Ygcoo+z3odc1aNn2bmHyebz8VoBUq31UoL8Ag20TscxFOLdb3YjXVCvAUrJNXRFd2AY5eYOe6WRGmWYlujjRPj1Z8QCgg8i1cCdfBy0tbgtTAjwex/bIU+UpP1DQZHxQidsge7yN0uFzxxYHKbkmKuGbKrYndABJEAWTLTFAPSZFaaNvPPn6x1pB9uZp9f2y/oQfmRMzY1pqJibe/Qy+KhX5LCvq3ThUiNxDIDnuKlyuUvWUzbFjkdxTtPXUHmgQ52cK+OVreNcydRhFMrksuWy2TidKmzpiDdakPLbvCQXxhozDr78tmNY8ju+nYTX0Aznd5FFNeA1l+BrP/f4Lky4GEhB/hWqIcLS1KGikYSWTIvCuepKACMCV2kO1l7vIP2KgROuvDmrEKzWlnbJYLmoiMHlwHsCD88vmfsbqegabJID3VomqT/aeBQlwwzDRJjMjpguqWXvNNtjEhP32XeKJoTfviEEqOQYieheXC1DtpUScm9kfv1n8NrrX8zMc0YIflIvKA/sJozGt05/aim/QDjRaGSUpjw2WcceqUl+JPZ5lxjNIghFXCZYlOm/keuqRpoJJ/f/eMzVY8/TwEr+ArNrTQwuFsbZSLGU+Stv/3ktU0pg31hB20ZeTSfmo/iWdbKy8ivbo2DZpURIFaLhfxaRCueLhkv2IoEysCVGXJtlf5GuXOMJqFErxxSkJuA3mttpIs0EPWX4EoUWdwwsNA2cwUk4TC6btiwQIGcoDYKnO/KqJAktN2BwG3r5M43kTcvl7U/EZx9T1wwRisu92wOcxyZArAaDfUl92gTGfyw5Gx9nyhIgaZVJ99ii6/aXRVK3hao+0ltTmCasmrznQAJ6l4A+s2jog/+BkEYSSTcImy9Fx3lzBGFsvu0THnCdbgJASNOVgyxVTFDEHwOo148eFIiRkDmdRhK8HmjBGkJi1kwCYTszw9xswOdXFP/4s2SMfFtbTyi4+FpTjz0JU1+oSWjs+R+m2V/MfVgBu2Mw+WeDe4ZbKz/11TJgic5lLjT1Yzi6ig9V+3LO8rtFfOH4MoaPB0eCe/U2HkqKwcfrNmHXtjy2SfYLJdbZRySgqpj/jsSodAR+E/fV0gG3Y37fOv3QCyHSpDR635Q1lKhxQdrRIQnIpGXSH8KYCbChstQLVn1ph0vpGXZkFKJyp/BuLcSIhAK07jVSCsgj7dqXTKW1QbL/+fmVjyfOhmJ4OaT4n42vcdCOn9c5LfPxAUd0OwG4BraAbGzi/hZXHkZFTPZJd3k4tw5qlNns=,iv:+9r6Ts484OUNrBdMAMP1veZ673zUHnFFFs3I0zgU+7I=,tag:tFo/WDncFqz8m7til/SDJg==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1anE5RGYyOWJlR0NtcE5O
            TXlwSnJLZEtka3VXZjdLT0R5RVZYZDRKU0M4CjI2N2dqd3FRZ0o0ZnRVdDJTZzZP
            THlZYml6c1htTVh5eWMweFV1REVvMWcKLS0tIHFNUkJGZk03Q2ZBb0kwU0xrVzRt
            aVRVOHkzaDdKcnJHZ0I1RmtiTnlmY00KotBE+QRpWcjKL6C6zgshzdB6rzyaEId3
            LDu+lqpMSQp3eInmEezbJOtHxLqpggV/PEbOUfW2WelMDfCHIKcx+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T03:53:32Z"
    mac: ENC[AES256_GCM,data:PK1auKWPoFUATuHIjdlDUH+81F/B0YJ2O7gts78ujFQkMRQZ+uLBaWEF5a5twHkO1tOvsiAAqbjqgI6vnyu4+vj8cZIKOEl4PwKBjQZPiK5ZvMbCXYEWKhiiHmxw5U3q0OaNzJQXxkb4Tf6aqKWW7x31ts0ftLx45uN/ZwoURqI=,iv:hAGTGBGhY0gharkUEmO2KwBaBWEGVIkr+05qEg/feLw=,tag:nEfGsFvppNbvPt+sRJh5Mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
