apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: nfs-config-secret
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:1Ptfiry4W6q07ZLbT6r+ksXQHT8mBZ7ulkRJJd9hRhm03IccfiEgggz70GsWPnd5hjQB0IYzAKBeOsyYg5GZfU5bQAtiLK7CQwlOsXSnfyIlxqecIScImC38lVnmB36DQu/s45gLnenlu1Pbzqhqg2guwSFFZc/RBIeb5ar1V7JlmpRuHcQmBeAgi2dwrJ727aC32riF/ncrmXWQjq487211hzd4xezIBkJDxpUWVJL01fMDLd4BOyTXUroKvq+TujSRflI+S1rZp+GmkPkNw4sBr/bI5lT9kXgirUulkqLWTxfVpqd4CTKOQKvT+mhY8HbPdCdXn6JkUxjN8mdEi1Y2v+nFezNOO3FbBQliBB5IxMYcLoH68sChxDBTjs27yPS2aY59V+nNJstEYmT0RYOxO5AZOjqN36oByY/D3oW7ku6fGKvVO6GeSKrPvXIqk5je4jX4NqUs4g66iUTozWExZewUlrz7IA4AOW62xIyalfpGp0wK6Q+rdoMD4Ws+/IxNQtddTISySMViENAOPvsQCQcjgWiGR17nYqmPsFVMlGSgQ4yizW6MFfXvQhQzRtBbDuWWn0lEa6wTMGpk/Ku7M+ZSLvpJQl8v/aA/+xoRJPF9Yw0BSk9142QxkLJYKMbZEm4w7HxmKSVGyVyCLomjDfwj2JBkkF3A06WHodSlo4sfZygEmC+Zkz4qrpWSZD13hu5BFxpBZc5CgtEbwsaFD0MlJtPiAQwGUmDcsxJe8eZrY0xlkH0HAOAeIYEAvtlJ1byTGXAubUdabkMEgN5/YjuCboP9RrpPO5mH9dm/ePO0l+lcoQJzi0ctfyKPnP8CVs4okYr+OyvxUYUFUwiykV1r7rUK1gNDwkDxwDM6dDw5+lyBEfkxXO/x7AnLnF6e3rDFtswqM0kdsKwcUMURBjAvmaABW9VD2t67bGP1515BikeEVxBubzAoJs1BmJqMjfwdwnrzfqZSn+0VBrlNS1rGDpeNZaLzD771urKMY3paJG4V9+SaPLAX5WEv+uxWkZ2GkQgoZgFPv+rhmfQTpZxd9VDfnvuBWbH4aV4Dm5SgWG0fJPYbRpG8EuTeS1uid5jjTrtFJu/66jQaC2zZro4UD1wroiQypVrAU3/Oizf9yrN2K5OtBp25J4ik2P3yymyVl7mr8Ou2Gpd36mp9At9K/gto9N2MKRAF28/glQ8v++22Vv1Cj4vZEKfarLC7SRpGt434RAEVJSEUtdme5L/sLzoENoPTpr2C5ma0iyjzCsNVV6D2I3zLoKCeYFlEmg==,iv:J3EK/9VgiKaGjAF4HtdDAxvPjwU+SPL/9xwLJkGiSdk=,tag:gJfJSa3Ae4JB/V+EQwayNA==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1anE5RGYyOWJlR0NtcE5O
            TXlwSnJLZEtka3VXZjdLT0R5RVZYZDRKU0M4CjI2N2dqd3FRZ0o0ZnRVdDJTZzZP
            THlZYml6c1htTVh5eWMweFV1REVvMWcKLS0tIHFNUkJGZk03Q2ZBb0kwU0xrVzRt
            aVRVOHkzaDdKcnJHZ0I1RmtiTnlmY00KotBE+QRpWcjKL6C6zgshzdB6rzyaEId3
            LDu+lqpMSQp3eInmEezbJOtHxLqpggV/PEbOUfW2WelMDfCHIKcx+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T02:59:35Z"
    mac: ENC[AES256_GCM,data:d7tXyJfpdcxbBQzD3IjdI9aXk4+gT7/mfd/D8/HXNiGmtb3va5mScfPvHX7PCuktkxJ7EOfKrm+gkluM26mV5+q980iVl3kuGtd4WGUqJONWW85FCEk9QXEH5mDhPZN0/Yyd3bzRfAhOkFrlotMvGeQwQwa99+321Es8SPw/miA=,iv:RGGbRM1W4JYcnElojVU1DYE9adoxZkrhzuFbZC6BPEY=,tag:smwFsxe/Aarsi4IEuVTgqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
