apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-driver
  namespace: democratic-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.x"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
      interval: 10m
  valuesFrom:
    - kind: Secret
      name: nfs-config-secret
      valuesKey: driver-config-file.yaml
    - kind: ConfigMap
      name: nfs-config
