apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: filestash
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: storage
resources:
  - statefulset.yaml
  - service.yaml
  - pvc.yaml
  - http-route.yaml
  - configmap.yaml
