apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
commonLabels:
  app.kubernetes.io/name: democratic-csi
  app.kubernetes.io/part-of: storage
resources:
  - repository.yaml
  - nfs/
  - iscsi/
