apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/component: infrastructure
resources:
  - namespace.yaml
  - alerts/
  - cilium/
  - democratic-csi/
  - traefik/
  - cert-manager/
