apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: immich
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: storage
resources:
  - release.yaml
  - repository.yaml
  - pvc.yaml
  - http-route.yaml
configurations:
  - kustomizeconfig.yaml
configMapGenerator:
  - name: immich-values
    files:
      - values.yaml
