# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.3.0/charts/library/common/values.schema.json
immich:
  persistance:
    library:
      existingClaim: immich-pvc
