apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
spec:
  secretName: traefik-cert
  dnsNames:
    - "k8s.nyumbani.home"
    - "*.k8s.nyumbani.home"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
