apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/instance: nfs-driver
resources:
  - iscsi-config-secret.secret.yaml
  - iscsi-config.yaml
  - release.yaml
