apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iscsi-driver
spec:
  interval: 10m
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.x"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      interval: 10m
  valuesFrom:
    - kind: Secret
      name: iscsi-config-secret
      valuesKey: driver-config-file.yaml
    - kind: ConfigMap
      name: iscsi-config
