apiVersion: v1
kind: ConfigMap
metadata:
  name: filerise
data:
  TIMEZONE: America/New_York
  TOTAL_UPLOAD_SIZE: 10G
  SECURE: "true"
  CHOWN_ON_START: "true"
  SHARE_URL: https://files.k8s.nyumbani.home/
  FR_PUBLISHED_URL: http://files.k8s.nyumbani.home/
