apiVersion: v1
kind: Secret
metadata:
    name: filerise
stringData:
    PERSISTENT_TOKENS_KEY: ENC[AES256_GCM,data:b84AMMbeAht8pGp/weN7/lVoUl74Kf2ovOA6QI31IV0oyflEjdZ87ocwWais,iv:BkhU4LW5bp1XT+Y5QGg5+s95bzokn+/47PsBytnpR7c=,tag:OP94ja+cAlV+aaQ31+VS3w==,type:str]
sops:
    age:
        - recipient: age12lrc9t2pdfxkfr08wre8w4nu7d623hf56lwrdpd3we4yaxs665zsdrxmm7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWmJGREpEeXIvRWxpcFJV
            NWhiQXdOek1ldytzcjF1ZjRKVUlvcURXM3dzCkJ4TTM0VmgrRjRHTU5BZFZmamIx
            Y05La3Y3Q3BsM3BUVXZyR2w0MElXSjQKLS0tIGJGVEdQejdDZitaaEN0UUtRM08x
            bFpyOTBqeXdvSTMxOHp1azVWR1R0ZkkKT8lOjazHR1anznUPcAKR30YS1RN0unoW
            GRkMQTAQBI9dv0foAKeMGZIf8whmRJII7gHsU2J8SJbRwLAuqTjd3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T21:36:42Z"
    mac: ENC[AES256_GCM,data:ofrqhgPeuphMo0cRGiqGwkKGeL68WP3Y8czhUKsZBkox0B05dDyg/3ADtP+M8FHBBDXoAN685qs8MeYMgL0sPN83NU1etQ1KIMRY9861tUl6xoW7VxgyyjbIp+PJ90YZgeAOm5jIVmScldHSxXo1PlW0mXkWGvoBK76q7XOvsKg=,iv:EJLgWXN3izgsLKJEpKPZs8jK+nTIxk2ETpCX1966cX0=,tag:eZRzmPsbNqpFnXYWeE+9Tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
