apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-driver
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.x"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      interval: 1h
  valuesFrom:
    - kind: Secret
      name: nfs-config-secret
      valuesKey: driver-config-file.yaml
    - kind: ConfigMap
      name: nfs-config
