env: ENC[AES256_GCM,data:tCiE9iwE/9jY51caE7EXbVZ4fzkBLCpeAQXE/7NZo2ZCVTty44xDc0pG467kXyuVt4Bm0Q==,iv:T4ibZu154O/YdddIYBZGPw0fEzrJebLDpQCmNt9JVac=,tag:Rq8T56L62CHJJRJX+Na86w==,type:str]
sops:
    age:
        - recipient: age15t03480ytxzadgwlan2hms049qtjyvt6uyyhv0s2a2lu45ltpu5sdfxg4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEd3BXL3BaQVhJQnJhTWVN
            dmRNVU04cVBWZGxzdFdOVVk5TmMyNTl6WGtrCkJ6SHAwcm5CbUJQVXNwVEkvWElr
            QWlreFFJa2pOTmFxdThlOWxJMTZNVGMKLS0tIGZQUVdFa21QTTEzc3JuRFRmS1NC
            NGhYbDZHb1d6R0lIbWMxN2RBbmdmZncKIuNi15tAOMl3KXWEeODgQIbcue6Pf4vd
            C772XpHsvWB6ZXj9Y7cSjdevzgXd8NcSURosuLeBm4Tf2ayfwlipEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xfwuvqdup6uasvn8xp855nvnr57454ywuqnyv8c4cx7l6e84yuxqgq3srv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSjAwSXQxSEtQZ1c4eDdX
            d1ZiUnM5bnRYWkNOcHcvQWtqNXBId29CU0EwCmo0YWZIYUFkeENOQlNaUlJOditl
            TVU5MnhpYkFYU3dacGIya2VkUkFXOHcKLS0tIFJmYlVqQjRpVmh3RlYxRGNYMmUv
            RFBnb0czczUyTFV0aCtzeXl0YTdBSjAKU8vXR9/RUW99QuyG0O0RSzxVBrZsr8c6
            D0aaNlrm3HHd8PJVQvPmdgegkunYcyieeIC2/Tif59NeMA1f8wvZAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T22:57:44Z"
    mac: ENC[AES256_GCM,data:RXD5PjyiHtvSsf8UgaCbh7DqUD4I6BPs9TqAUj7JkzEG/vPyYJGck1HY/tWLHa70hOIy81CbYY3UpNF3ufEgOqxO/9WQYVF5AU9QmzvJNMUy/UkpHaozoob6t2/gihy9q1RrhC6my9AKMRpFWRnpe92HwBGdgtz9bBb92B4IOXo=,iv:x9MzxM5IAnoeX9axdu1Efx9Lb8zVGGi1Gza0gUZkoCE=,tag:6quZ8YObrruD/6GLKyRCnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
