env: ENC[AES256_GCM,data:tCiE9iwE/9jY51caE7EXbVZ4fzkBLCpeAQXE/7NZo2ZCVTty44xDc0pG467kXyuVt4Bm0Q==,iv:T4ibZu154O/YdddIYBZGPw0fEzrJebLDpQCmNt9JVac=,tag:Rq8T56L62CHJJRJX+Na86w==,type:str]
sops:
    age:
        - recipient: age1usfdmdtlaem6x5pc6zkvn0h6tnlylpe6wxedg95k4svz5vjsyy8syjuhhp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd0hPYzVWUkVOaEU3MlJr
            ZUdXaXpUa2J2YW9lSGhzWGV5K2xEblRwaGtZCmdhN1hjdGpBcnBsSXhTckQxeERu
            OUliNDdXZmVRekpYVkl0QU1hdng5S2MKLS0tIGdHT3MzVkE3NjhtWGNKQ3VkeGUz
            TFVHbm9vV2pJeXlVbFoxbUZXeTdWcUUKGx00mnXIk4fLabOl09w4+cu52ca6Y/j1
            G0SeHesQ1dsqci2TbgXNTC339HYFQWlJFWZCylsxOb/CRHjuh7vtxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xfwuvqdup6uasvn8xp855nvnr57454ywuqnyv8c4cx7l6e84yuxqgq3srv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZzRqL3o2YUN1U3dUTGJa
            K0o2VGFQUHBjT09obll6anFPRndyNnUyaEdRCllYWFc0SUJya0N6RXFSbnpXTEZC
            S3Q2SVJ3SmhmbXVnQk5VbEhLRjdHcTAKLS0tIFVIQjhCdFpnRjVlZjJucGM1VmRY
            MWtzNndueW9GOVYzQ216R1Bwek1yck0KDYHhgrDN/6QHIzrPXDeS3yvrUPN6rWTU
            0XCsu4+Lr4XxvBCP/wPpDlXsLXgOj7pL6Idda2XIVmxidmquTNblMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T22:57:44Z"
    mac: ENC[AES256_GCM,data:RXD5PjyiHtvSsf8UgaCbh7DqUD4I6BPs9TqAUj7JkzEG/vPyYJGck1HY/tWLHa70hOIy81CbYY3UpNF3ufEgOqxO/9WQYVF5AU9QmzvJNMUy/UkpHaozoob6t2/gihy9q1RrhC6my9AKMRpFWRnpe92HwBGdgtz9bBb92B4IOXo=,iv:x9MzxM5IAnoeX9axdu1Efx9Lb8zVGGi1Gza0gUZkoCE=,tag:6quZ8YObrruD/6GLKyRCnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
