env: ENC[AES256_GCM,data:vQ5PRg6w0py5QYwX71QQLZlA6NpcuW65+3lvVC6JQm5KWpVN5xXgWQP73TW6ulQW9uj2Gw4QZpkydQ==,iv:1fZNFAaw+mOs5OOi/MGS+JQmSCg+0aV5Dj4h6Kt/Y2U=,tag:imrQ30wDVqToVti4F7+MjA==,type:str]
sops:
    age:
        - recipient: age15t03480ytxzadgwlan2hms049qtjyvt6uyyhv0s2a2lu45ltpu5sdfxg4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOFlydVdFdWZrZkxpdVcv
            cXV6anlQNC9GWUhhaG9JL0ZEMUFoK0JIeWtrCnhnNjZsQjJ0SXdXSXUyeVNJRHhQ
            SCtsejA2ekoxYXBKNkxGT1VZK2Z4L00KLS0tIFdUQkp3U2QvV282Z2N2am80Q1Uz
            VHhRYjBRRlpSeUwzeHFFY3NoZTVSVXcKexNIDHs+1NVUsz02Z3Ce0RI1UQPlEqOr
            Dc+B5zfKfsctyMI2BLQlZhFMnqdlX9q1vV9YSfT+c3XMvp7qCUB4dA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xfwuvqdup6uasvn8xp855nvnr57454ywuqnyv8c4cx7l6e84yuxqgq3srv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L09Xc2pOcXRGY3JiUHdF
            TTgzVU04blVlNlFBclBFUThGTXR1RjhjamowCk5xNURGbGw4ZFhUSHUvOHFEWXFZ
            b05IWmVQT2wvWjY5S1FQSkJiVU4vRXcKLS0tIFV2VHQvOHhYMXFxQVpwVldSM1dT
            WDBiT2xZZXpmbWM5QXYzMm4wTUlGN00KLXvMrmbj1PLPDE/b3OEYjCtP15tBrrOv
            2M3ujGtUv9TtYAL9TqLXeUdQn6R7JPZnCPcKhpZ8lDEsVoCV0qqaHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T21:43:39Z"
    mac: ENC[AES256_GCM,data:26igOP72527Rxwc3LH5Z4ojTd2c34Yy3a+++Jnwz+N4AI2j1WgI5r5rJsHFJo4lrXaIzaI1MsnpOJ6iRRP4hXgFpDv5lSZ21yQ/9Wx8VicKPDrYmfDnLvfV5f8k8E0nUJfmLQjWYdYFTCn3f+uPx/pQl44iJfgyfa1ruTpbxGgU=,iv:9ZSBzW9CR1OC349/ntcLpPlW/j5HKxQKiMomlm1VNjY=,tag:stmclLNMLWgTDA8wDvDoEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
