"$schema" = "https://www.schemastore.org/traefik-v3.json"

[global]
sendAnonymousUsage = false

[log]
level = "DEBUG"

[api]
dashboard = true
insecure = true

[entryPoints.web]
address = ":80"
http.redirections.entryPoint = { to = "websecure", scheme = "https", permanent = true }

[entryPoints.websecure]
address = ":443"

[certificatesResolvers.cloudflare.acme]
email = "info@kaptcha.cc"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
keyType = "EC256"

dnsChallenge.provider = "cloudflare"
dnsChallenge.resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
