apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi
labels:
  - pairs:
      app.kubernetes.io/name: democratic-csi
      app.kubernetes.io/part-of: storage
resources:
  - namespace.yaml
  - repository.yaml
  - nfs/
  - iscsi/
