apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: cilium
  app.kubernetes.io/part-of: networking
resources:
  - repository.yaml
  - release.yaml
  - values.yaml
